openapi: 3.0.2
info:
  title: organizational-structure-service
  version: 1.0.0
servers:
  - url: http://localhost:8080/ordering-system-gateway/api/v1

security:
  - basicAuth: [ ]

paths:
  /orders:
    get:
      operationId: getOrders
      responses:
        "200":
          $ref: "#/components/responses/GetOrdersResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
    post:
      parameters:
        - $ref: "#/components/parameters/Authorization"
      operationId: addOrder
      requestBody:
        $ref: "#/components/requestBodies/AddOrderRequest"
      responses:
        "201":
          $ref: "#/components/responses/AddOrderResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /orders/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - $ref: "#/components/parameters/Authorization"
    put:
      operationId: processOrder
      responses:
        "202":
          $ref: "#/components/responses/ProcessOrderResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
components:
  parameters:
    Authorization:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
  requestBodies:
    AddOrderRequest:
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/AddOrderRequestData'
  responses:
    GetOrdersResponse:
      description: Успех
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/GetOrdersResponseData'
    AddOrderResponse:
      description: Успех
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/AddOrderResponseData'
    ProcessOrderResponse:
      description: Успех
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/ProcessOrderResponseData'
    ErrorResponse:
      description: Ошибка
      content:
        application/json;charset=UTF-8:
          schema:
            $ref: '#/components/schemas/ErrorResponseData'
  schemas:
    GetOrdersResponseData:
      type: array
      items:
        $ref: "#/components/schemas/Order"
    Order:
      type: object
      required:
        - id
        - name
        - price
        - customerId
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
        customerId:
          type: integer
          format: int64
    AddOrderRequestData:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
        price:
          type: number
    AddOrderResponseData:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
    ProcessOrderResponseData:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    ErrorResponseData:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
        originalCode:
          type: string
        originalMessage:
          type: string
        details:
          type: array
          items:
            type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic