GRANT USAGE ON SCHEMA orders TO orders;
GRANT ALL ON ALL TABLES IN SCHEMA orders TO orders;
ALTER DEFAULT PRIVILEGES IN SCHEMA orders GRANT ALL ON TABLES TO orders;
GRANT ALL ON ALL SEQUENCES IN SCHEMA orders TO orders;
ALTER DEFAULT PRIVILEGES IN SCHEMA orders GRANT ALL ON SEQUENCES TO orders;