GRANT USAGE ON SCHEMA executors TO executors;
GRANT ALL ON ALL TABLES IN SCHEMA executors TO executors;
ALTER DEFAULT PRIVILEGES IN SCHEMA executors GRANT ALL ON TABLES TO executors;
GRANT ALL ON ALL SEQUENCES IN SCHEMA executors TO executors;
ALTER DEFAULT PRIVILEGES IN SCHEMA executors GRANT ALL ON SEQUENCES TO executors;