GRANT USAGE ON SCHEMA customers TO customers;
GRANT ALL ON ALL TABLES IN SCHEMA customers TO customers;
ALTER DEFAULT PRIVILEGES IN SCHEMA customers GRANT ALL ON TABLES TO customers;
GRANT ALL ON ALL SEQUENCES IN SCHEMA customers TO customers;
ALTER DEFAULT PRIVILEGES IN SCHEMA customers GRANT ALL ON SEQUENCES TO customers;