GRANT USAGE ON SCHEMA users TO users;
GRANT ALL ON ALL TABLES IN SCHEMA users TO users;
ALTER DEFAULT PRIVILEGES IN SCHEMA users GRANT ALL ON TABLES TO users;
GRANT ALL ON ALL SEQUENCES IN SCHEMA users TO users;
ALTER DEFAULT PRIVILEGES IN SCHEMA users GRANT ALL ON SEQUENCES TO users;